;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	backward-sexp
	counsel-M-x
	forward-sexp
	hungry-delete-forward
	lsy-kill
	lsy-kill-region
	lsy-yank
	mouse-set-region
	overwrite-mode
	py-electric-colon
	py-electric-comment
	undo-tree-visualize
	))

(setq mc/cmds-to-run-once
      '(
	hungry-delete-backward
	undo-tree-visualize
	))
