;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	anzu-query-replace
	backward-kill-sexp
	backward-sexp
	c-electric-brace
	c-electric-delete-forward
	c-electric-paren
	c-electric-pound
	counsel-M-x
	forward-sexp
	hungry-delete-forward
	indent-for-tab-command
	lsp-ui-doc--handle-mouse-movement
	lsy-kill
	lsy-kill-region
	lsy-yank
	mouse-set-region
	my-backward-delete-word
	my-delete-region-no-kill
	overwrite-mode
	py-electric-colon
	py-electric-comment
	undo-tree-visualize
	))

(setq mc/cmds-to-run-once
      '(
	beginning-of-buffer
	hungry-delete-backward
	ivy-switch-buffer
	lsy-python-eval-line
	lsy:copy-file-name
	mouse-drag-vertical-line
	swiper
	undo-tree-visualize
	upcase-region
	))
