;;; Automatically generated by ‘recentf’ on Sun Mar 12 23:06:16 2023.

(setq recentf-list
      '(
        "/root/.emacs.d/lisp/init-tool.el"
        "/home/lishiyu/Project/explore/order_flow_test.py"
        "/root/.emacs.d/init.el"
        "/root/.emacs.d/lisp/init-python.el"
        "/root/.emacs.d/lisp/init-local.el"
        "/root/.emacs.d/lisp/init-company.el"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
