;;; Automatically generated by ‘recentf’ on Tue Mar 14 10:29:49 2023.

(setq recentf-list
      '(
        "/root/.emacs.d/lisp/init-python.el"
        "/home/lishiyu/Project/explore/order_flow_test1.py"
        "/home/lishiyu/Project/bin_tools/bins.py"
        "/home/lishiyu/Project/explore/order_flow_test.py"
        "/home/lishiyu/Project/tick_strategy/test.py"
        "/home/lishiyu/Project/tick_strategy/feature.py"
        "/root/.emacs.d/init.el"
        "/root/.emacs.d/lisp/init-keymap.el"
        "/root/.emacs.d/lisp/init-ui.el"
        "/root/.emacs.d/lisp/init-local.el"
        "/root/.bashrc"
        "/root/.emacs.d/elpa/python-mode-20211013.1620/python-mode.el"
        "/root/.emacs.d/lisp/init-company.el"
        "/root/.emacs.d/elpa/company-20211002.1732/company-capf.el"
        "/root/.emacs.d/elpa/elpy-20210630.2317/elpy.el"
        "/root/.emacs.d/lisp/init-tool.el"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
